# Generated by Django 3.2.4 on 2021-06-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id producto')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='nombre del producto')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='descripcion del producto')),
                ('image', models.ImageField(default='no_stock.jpg', upload_to='images/', verbose_name='imagen del producto')),
            ],
        ),
    ]
