# Generated by Django 3.2.4 on 2021-07-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtesanosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='nostock.jpg', upload_to='images/', verbose_name='imagen del producto'),
        ),
    ]
